language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - ./node_modules/.bin/mockatenate
  # set up necessary for testing with Firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - ./node_modules/.bin/coveralls < coverage/PhantomJS*/lcov.info
notifications:
  email:
    - pete.haughie@sourcefabric.org
